# Redirects from what the browser requests to what we serve
/home                /
/articles/category.js    /client/pages/articles/category.js
/articles/post.js         /client/pages/articles/post.js
/articles/NoPost.js   client/pages/articles/NoPost.js

[[redirects]]
  from = "/search"
  to = "http://13.233.72.215:4001"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From: "Netlify"}
  signed = "uaaEx0brWSpIABBPAZ1NcFMW3I2lB7-qO_G_NCerROw"
